[package]
name = "effect-local-fs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
psk-types = { path = "../../packages/psk-types" }
psk-effect = { path = "../../packages/psk-effect" }

[build-dependencies]
psk-codegen = { path = "../../tools/psk-codegen" }