[package]
name = "observer-local-fs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
psk-types = { path = "../../packages/psk-types" }
psk-anchor = { path = "../../packages/psk-anchor" }

[build-dependencies]
psk-codegen = { path = "../../tools/psk-codegen" }