[package]
name = "observer-local-fs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "observer-local-fs"
path = "src/main.rs"

[dependencies]
psk-types = { path = "../../packages/psk-types" }
psk-anchor = { path = "../../packages/psk-anchor" }
psk-ipc = { path = "../../packages/psk-ipc" }

[build-dependencies]
psk-codegen = { path = "../../tools/psk-codegen" }